notepad Audio3DTest\pch.h
notepad D3D12Test\pch.h
notepad EffectsTest\pch.h
notepad EmptyTest\pch.h
notepad HDRTest\pch.h
notepad KeyboardTest\pch.h
notepad mGPUTest\pch.h
notepad ModelTest\pch.h
notepad MouseTest\pch.h
notepad PBRModelTest\pch.h
notepad PBRTest\pch.h
notepad PostProcessTest\pch.h
notepad PrimitivesTest\pch.h
notepad ShaderTest\pch.h
notepad SimpleAudioTest\pch.h
notepad SpriteBatchTest\pch.h
notepad SpriteFontTest\pch.h
